id = "zed-vint"
name = "zed-vint"
description = "zed's vintlang language support"
version = "0.0.1"
schema_version = 1
authors = ["Tachera Sasi"]
repository = "https://github.com/vintlang/zed-vint"




